# Site settings
title: Space Warp of Amazing Stuff
header-img: img/photo-header.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
logo: /img/kilix-logo-blog.png
baseurl: ""
url: "http://yourdomain.com"

github_username:  Kilix

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
